### ISSUE TITLE
Possibly eliminate race conditions on review-site github action

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1902] opened 2022-09-16 20:25 UTC
Currently the https://github.com/az-digital/az_quickstart/blob/main/.github/workflows/review-site.yml workflow that runs after merging a PR into main experiences a race condition if another PR is merged in quick succession.

The workflow changes the codebase of the site whether or not there is an existing running process for installing quickstart (which needs the codebase to not change during install).

The solution to this is to separate the install command out of an environment that can have code changes during install.

Possible alternative workflow.
The [update code](https://github.com/az-digital/az_quickstart/blob/main/.github/workflows/review-site.yml#L31) step should create a multidev environment (minus the database and files).

When it is done, it should be able to overwrite the database and codebase from the multidev without reporting back an install error.

**Comment by joeparsons** [comment] 2022-09-16 20:31
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

**Comment by joeparsons** [comment] 2023-01-25 18:46
Duplicate of #2109.  Fixed by #2153.

**Closed by joeparsons** 2023-01-25 18:46 UTC
Labels: ci
