### ISSUE TITLE
Carousel feature is off center and appears broken on large displays.

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#2857] opened 2023-10-23 21:58 UTC
## Problem/Motivation
I was looking at the in process website for the Center for Semiconductor Manufacturing on a large monitor and noticed that it looks very broken on large screens. 
![Screenshot 2023-10-23 at 2 48 24 PM](https://github.com/az-digital/az_quickstart/assets/1509771/07df995a-92dc-4f0a-b5da-379f74595e10)

I first noticed this on a screen size of 2545 px wide, but it looks like the previous and next previews start to separate from the featured image starting at 1750 px.

**Comment by bberndt-uaz** [comment] 2023-10-23 22:08
See also: https://github.com/az-digital/az_quickstart/issues/1428

**Comment by joeparsons** [comment] 2023-10-26 21:09
Closing this as a duplicate of #1428

**Closed by joeparsons** 2023-10-26 21:09 UTC
Labels: bug
