### ISSUE TITLE
Card Title Text-Align Options

### ISSUE THREAD

**Issue by JoeLutovsky** [az-digital/az_quickstart#3175] opened 2024-02-15 23:14 UTC
### Describe the solution you'd like
Would be helpful if there were text align options that set the text alignment of Titles within Cards rather than them always being left justified. 

## Additional context
Sometimes centering the card title text would look better.

**Comment by joeparsons** [comment] 2024-03-07 18:47
This is probably a duplicate of #2037

**Comment by joeparsons** [comment] 2024-03-07 18:51
Closing this since we already have #2037 which has a pending PR (#2041)

**Closed by joeparsons** 2024-03-07 18:51 UTC
Labels: enhancement, editor experience
