### ISSUE TITLE
Close icon broken in media library edit module's modal

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#2169] opened 2023-01-20 19:46 UTC
## Problem/Motivation
While testing a recent update (dependabot PR) for the Media Library Edit module, @bberndt-uaz noticed an issue with the close icon in the modal dialog used by the Media Library Edit module included in Quickstart.

### Describe the bug
From https://github.com/az-digital/az_quickstart/pull/2128#issuecomment-1377629526:

> This update introduces an issue with the close button on the pop-up for editing media: when hovering the cursor over the button, the appearance is incorrect.
> 
> Before this PR:
> ![](https://user-images.githubusercontent.com/74572157/211622512-7bb313b4-1c58-4c62-8335-79ce6e6ac196.png)
> 
> After this PR:
> ![](https://user-images.githubusercontent.com/74572157/211622620-1cb1908d-2205-422a-a5a6-6ea4c197020c.png)
>
>It looks like the .ui-icon background image is now being loaded from /core/assets/vendor/jquery.ui/themes/base/images instead of /core/themes/claro/images.

This bug seems to be associated with this change that was made to the module ahead of the 3.0.0 release:
https://www.drupal.org/project/media_library_edit/issues/3292509

## Proposed resolution
Contribute a patch to drupal.org for fixing this issue since it likely affects anyone using the module with Paragraphs and the Claro theme.

**Comment by bberndt-uaz** [comment] 2023-01-20 22:07
I was able to reproduce this bug, which seems to be related to our card deck paragraph type. Quickstart 2.5.1 is not affected. However, I could reproduce the issue in [this media_library_edit Probo site](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2128.probo.build/brian-test-page) as well as [the Probo site for another recent PR](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2165.probo.build/brian-test-page-2).

Steps to reproduce:

1. Create a new flexible page
2. Add a card deck
3. Add another paragraph type with media, such as Text on Media
4. Add an image to the second paragraph
5. Click the pencil "edit" icon to view the incorrect appearance for the close icon
6. Reload the page
7. Edit the second paragraph, edit the media item, and observe the correct close icon
8. Click to edit the card deck, then return to edit the media item in the second paragraph and observe the incorrect icon

In other words, every time you open the card deck to edit it, the media close icon gets messed up. From that point on, opening the media edit pop-up produces this error in the console:

> Uncaught TypeError: Cannot set properties of undefined (setting '_renderItem')
>     at HTMLInputElement.<anonymous> (autocomplete.js?v=9.4.10:127:55)
>     at Function.each (jquery.min.js?v=3.6.0:2:3003)
>     at S.fn.init.each (jquery.min.js?v=3.6.0:2:1481)
>     at Object.attach (autocomplete.js?v=9.4.10:126:58)
>     at drupal.js?v=9.4.10:27:24
>     at Array.forEach (<anonymous>)
>     at Drupal.attachBehaviors (drupal.js?v=9.4.10:24:34)
>     at HTMLFormElement.<anonymous> (ajax.js?v=9.4.10:569:20)
>     at Function.each (jquery.min.js?v=3.6.0:2:3003)
>     at S.fn.init.each (jquery.min.js?v=3.6.0:2:1481)

The function that produces this error is this one:

>         $autocomplete.autocomplete(autocomplete.options).each(function () {
>           $(this).data('ui-autocomplete')._renderItem = autocomplete.options.renderItem;
>         });

Only editing a card deck produces this error: adding and editing the other paragraph types does not result in this issue.

I noticed that AZCardWidget.php was most recently updated with [this commit from Sep 7, 2022](https://github.com/az-digital/az_quickstart/commit/8562ffd69a95e769360c60e52d428de142f2579b) and it does add a couple "autocomplete" properties. However, I believe that code was merged prior to 2.5.1, which isn't affected by this issue.

**Comment by trackleft** [comment] 2023-01-20 22:14
I see it now

**Comment by trackleft** [comment] 2023-01-20 22:38
Looks like a css scoping issue to me, claro only sets the inline bg image on 

```
.ui-dialog .ui-icon.ui-icon-closethick
```
Instead of this

```
.ui-dialog .ui-button:hover .ui-icon.ui-icon-closethick,
.ui-dialog .ui-icon.ui-icon-closethick,
 ```
 In this file /core/themes/claro/css/components/dialog.css
 
![image](https://user-images.githubusercontent.com/1023167/213817273-4df076f8-402d-4802-9b4c-0f2d200e7435.png)

**Comment by trackleft** [comment] 2023-01-23 20:12
Added a Drupal core issue https://www.drupal.org/project/drupal/issues/3335935

**Comment by trackleft** [comment] 2023-01-23 21:06
Might need to add even more scope: ```.ui-dialog .ui-dialog-titlebar-close.ui-button:hover .ui-icon.ui-icon-closethick, .ui-dialog .ui-icon.ui-icon-closethick`` So we don't break other styles.

**Comment by bberndt-uaz** [comment] 2023-01-24 17:33
The JavaScript error that I [mentioned above](https://github.com/az-digital/az_quickstart/issues/2169#issuecomment-1399008690) appears to be a separate issue from the close icon appearance. In Quickstart 2.5.1, once a user has clicked to edit a card deck, an Uncaught TypeError on `_renderItem` is triggered every time the user clicks the pencil edit icon on a media item in another paragraph. However, in 2.5.1 the close icon is displayed correctly.

**Comment by bberndt-uaz** [comment] 2023-11-17 22:48
Unfortunately, this issue has reared its ugly head again with 2.8. The close icon does not appear on any "Add or select Media" or "Edit Media" modal dialogs from the Media Library Edit module:

![image](https://github.com/az-digital/az_quickstart/assets/74572157/71043094-994b-4426-a546-e4309db48e2e)

Button markup in 2.7:

```
<button type="button" class="ui-button ui-corner-all ui-widget ui-button-icon-only ui-dialog-titlebar-close" title="Close">
  <span class="ui-button-icon ui-icon ui-icon-closethick"></span>
  <span class="ui-button-icon-space"> </span>
  Close
</button>
```

Button markup in 2.8:

`<button type="button" class="ui-dialog-titlebar-close"></button>`

Removing the "Ajax CSS load order issue (1461322)" patch did not fix the issue. I have added this issue to the 2.8.x project.

**Closed** 2023-11-29 17:12 UTC
Labels: bug, dependencies, Drupal, editor experience
