### ISSUE TITLE
JavaScript error "Cannot read properties of null (reading 'nodeType')" on node add/edit pages

### ISSUE THREAD

**Issue by joshuasosa** [az-digital/az_quickstart#3190] opened 2024-02-20 01:54 UTC
## Problem/Motivation
JavaScript console is displaying an error message on node add and edit pages.

### Describe the bug
The following JavaScript error is occurring on node add and edit pages:

> Uncaught TypeError: Cannot read properties of null (reading 'nodeType')
>     at checkMutation (big_pipe.js?v=10.2.3:92:12)
>     at checkMutationAndProcess (big_pipe.js?v=10.2.3:116:14)
>     at NodeList.forEach (<anonymous>)
>     at big_pipe.js?v=10.2.3:129:18
>     at Array.forEach (<anonymous>)
>     at MutationObserver.processMutations (big_pipe.js?v=10.2.3:128:15)

Note: disable "Aggregate JavaScript files" to see where the error is coming from.

### To Reproduce

1. Install AZQS.
2. Go to add a node (e.g., Event, Page, etc.).
3. Review browser's JavaScript console to see the error.

## Proposed resolution
Issue has been reported in Drupal issue queue: [Cannot read properties of null (reading 'nodeType') on node.page.body (3413079)](https://www.drupal.org/project/drupal/issues/3413079).

Using the patch in [MR!6057](https://git.drupalcode.org/project/drupal/-/merge_requests/6057) resolves the error in testing:
https://git.drupalcode.org/project/drupal/-/merge_requests/6057.patch

I'm not sure if patches produced by Drupal merge requests are stable enough to use. If not, or if preferred, the patch in [#23](https://www.drupal.org/project/drupal/issues/3413079#comment-15410367) is identical.
https://www.drupal.org/files/issues/2024-01-23/3413079-cannot-read-properties-21-commit_8d9d804c.patch

**Comment by joeparsons** [comment] 2024-02-20 23:48
Thanks for reporting @joshuasosa!

**Comment by joeparsons** [comment] 2024-02-21 00:00
Looks like there is a duplicate issue on Drupal.org that has already been fixed (and will be included in the next Drupal 10.2.x release):
https://www.drupal.org/project/drupal/issues/3416141).

[Drupal issue #3413079](https://www.drupal.org/project/drupal/issues/3413079) has been closed as a duplicate of the fixed issue.

**Closed** 2024-02-21 18:05 UTC
Labels: bug, dependencies, Drupal, patch release
