### ISSUE TITLE
Remove dependency on Bootstrap Barrio ("fork barrio today")

### ISSUE THREAD

**Issue by camikazegreen** [az-digital/az_quickstart#690] opened 2021-04-27 22:48 UTC
## Motivation
Increasingly we find ourselves needing to override, unset, or removed styles or functionality provided by the Bootstrap Barrio theme that our Arizona Barrio theme currently extends.

## Proposed Resolution
We should "fork" Bootstrap Barrio (i.e. remove Arizona Barrio's dependency on Bootstrap Barrio).  This will require copying all of the base theme files/functionality provided by Bootstrap Barrio into Arizona Barrio.

### Describe alternatives you've considered
There have been several Quickstart issues we've merged PRs for that have added code to Arizona Barrio to unset stylesheets included in  Bootstrap Barrio's `global-styling` library, e.g.:
- #795
- #852
- #251
- #438

## Additional context
Starting with Drupal 10.0.x, Drupal core no longer ships with any themes that are recommended for use as a `base theme` and instead now includes a "Starterkit theme generator" which is the new recommended best practice for creating new themes (see https://www.drupal.org/about/core/blog/new-starterkit-will-change-how-you-create-themes-in-drupal-10, https://www.drupal.org/node/3305674 and https://www.drupal.org/node/3309392).

#### What is the problem that we want to solve?
There have been several choices made by the maintainer of Barrio that we did not agree with. 
We should reconsider whether or not we want to fork Barrio.

**Comment by joeparsons** [comment] 2022-10-26 20:18
## 2022-10-26 Workshop notes

### Steps required to fork barrio
- Determine whether to rename az_barrio and/or whether a new theme is needed rather than modify az_barrio
- Copy any templates that only exist in Bootstrap Barrio into Arizona Barrio
- Copy any PHP files included in Bootstrap Barrio that don't exist in Arizona Barrio (if any)
- Remove the `base theme` line in .info.yml file (last step)
- Figure out what is needed related to theme variables (config), i.e. to we need to create new variables or copy any from bootstrap_barrio?

### Potential stages:
1. Keep machine name as `az_barrio` but remove dependency on bootstrap_barrio
2. Change machine name in the future ?

### Follow-up steps
- Remove bootstrap_barrio composer dependency (when?)

**Comment by joshuasosa** [comment] 2022-10-27 01:17
I think the benefits of getting focused development updates on the theme from the general community could outweigh the minor issues that crop up from using the base theme. There was a case just recently where there was an issue that was going to be fixed that was already resolved with the base theme, just that AZQS hasn't updated the base theme for years. There may very well be other issues inherent in the current AZQS codebase that have been resolved with Bootstrap Barrio updates, which would not be addressed if split off until re-discovered.

An option of course could be to re-build the theme from scratch to not have any 'legacy' issues from using a base theme. But the ability to have a quick and easy jumping-off point, with community support and good UI-based appearance options led us to adopt a base theme.

In issue #795, yes it does look like there's table styling in the base theme when there shouldn't be. There's a [Barrio Bootstrap issue](https://www.drupal.org/project/bootstrap_barrio/issues/3314580) currently open for that, and it'd probably be more beneficial to contribute to that.

For the other AZQS issues mentioned, I couldn't find related Barrio Bootstrap issues. Were those issues brought up with the maintainers and subsequently closed? If not, I'd suggest working with and contributing back to Bootstrap Barrio instead of departing from it, until such a time where it becomes more a fundamental hindrance than a benefit. And as with other contrib modules, I'd suggest adopting a plan to actually update Bootstrap Barrio instead of relying on its years-old outdated version.

**Comment by tadean** [comment] 2022-11-02 16:09
It'd definitely be useful to have updates from the parent theme, but there are a few issues we've encountered that have caused some hesitance in updating the parent theme; we haven't really done a good job about documenting these but spoken about them in PR review. I'll see if I can recall some things we've talked about in the past here:

- Recent versions of Barrio include bootstrap source. This adds to distribution size for something we'll never actually use. There is a barrio issue for this [here](https://www.drupal.org/project/bootstrap_barrio/issues/3138347) that is somewhat stalled. I think this issue is why we stalled on updating Barrio originally.
- Our process of font inclusion doesn't use google fonts, which amounts to dead code in the parent theme
- Barrio is moving towards using layouts for media and cards, while we have dedicated types for these that aren't part of the theme
- We aren't really using the color functionality in the way barrio does
- Barrio mostly functions as a module that allows **"multiple ways to get bootstrap into your theme"**; SASS, dist, CDN inclusion, dist subtheme starterkit, etc. This results in some duplication in barrio that for us, only adds file size, since we already have our own CSS styles that are built separately from actual Bootstrap with separate means of inclusion.
- Many of barrio's recent templates are for replacing the normal core drupal markup with **bootswatch/color** changes, and this isn't functionality we're using.
- As Drupal 10 approaches, it's possible we might want to incorporate some aspects of Drupal's [Starterkit](https://www.drupal.org/about/core/blog/new-starterkit-will-change-how-you-create-themes-in-drupal-10) rather than Barrio.

I think on the whole some of the above mostly just amounts to the fact that the base theme is starting to make design choices that are at cross purposes to some things we already have in our distribution (Cards, etc). It's not that these things are an issue or problem in the parent theme, but they are changes in design philosophy we'd be overriding to avoid conflicts with functionality we already have.

**Comment by joshuasosa** [comment] 2022-11-03 00:10
> * Recent versions of Barrio include bootstrap source. This adds to distribution size for something we'll never actually use. There is a barrio issue for this [here](https://www.drupal.org/project/bootstrap_barrio/issues/3138347) that is somewhat stalled. I think this issue is why we stalled on updating Barrio originally.

It looks like trackleft2 noted that the libraries were removed in version 5. Is this still an issue? Other than that, it seems like it's easy enough to include the patch to solve the issue. And it doesn't seem like AZQS has any qualms about adding useful patches.

> * Our process of font inclusion doesn't use google fonts, which amounts to dead code in the parent theme

This is very much a non-issue. There's tons of things in Drupal core that aren't used and can be considered "dead code."

> * Barrio is moving towards using layouts for media and cards, while we have dedicated types for these that aren't part of the theme

How will the usage of layouts for media and cards negatively impact AZQS? As far as I've seen, AZQS relies on custom-built paragraphs that utilize AZ Bootstrap. Since Layouts are part of core, I think Barrio adding more support there is a good thing.

> * We aren't really using the color functionality in the way barrio does

I think it would be good to explore using the color functionality the way Barrio does. That was one of the reasons why Barrio was selected in the first place.

> * Barrio mostly functions as a module that allows **"multiple ways to get bootstrap into your theme"**; SASS, dist, CDN inclusion, dist subtheme starterkit, etc. This results in some duplication in barrio that for us, only adds file size, since we already have our own CSS styles that are built separately from actual Bootstrap with separate means of inclusion.

On the contrary, Barrio acts as a good platform for setting up regions, templates, theme logic and UI-based tools for site builders. Boiling it down to just getting bootstrap is missing the point.

> * Many of barrio's recent templates are for replacing the normal core drupal markup with **bootswatch/color** changes, and this isn't functionality we're using.

Unused functionality is not a good reason to exclude the entire theme. There's scores of unused functionality in both Drupal core and in included contributed modules, and it's not like AZQS is looking to split from all of those.

> * As Drupal 10 approaches, it's possible we might want to incorporate some aspects of Drupal's [Starterkit](https://www.drupal.org/about/core/blog/new-starterkit-will-change-how-you-create-themes-in-drupal-10) rather than Barrio.

When the time comes around when that's ready to explore, then more options can be examined. For instance, if there are new useful features that the new starterkit takes advantage of, it's very well possible that Barrio may incorporate it. If AZQS is eager enough to get onboard those new features, it would even be pertinent for developers here to help get Barrio on that track with issue creation and contributions.

> I think on the whole some of the above mostly just amounts to the fact that the base theme is starting to make design choices that are at cross purposes to some things we already have in our distribution (Cards, etc). It's not that these things are an issue or problem in the parent theme, but they are changes in design philosophy we'd be overriding to avoid conflicts with functionality we already have.

I don't see any issues raised here that calls for a complete split from a parent theme. It would still be better to continue working with the greater theme community than to silo the project off. In similar philosophy, it would be akin to splitting from another contrib module that includes other unused functionality, or splitting from Drupal itself since it includes unused features like Layouts (dead code).

**Comment by joeparsons** [comment] 2022-11-03 00:14
>It looks like trackleft2 noted that the libraries were removed in version 5. Is this still an issue? Other than that, it seems like it's easy enough to include the patch to solve the issue. And it doesn't seem like AZQS has any qualms about adding useful patches.

@trackleft, @tadean, and I discussed the recent updates to that issue a couple of weeks ago (including Chris' most recent comment on that issue) and Chris mentioned that upon checking again, he realized he had been looking in the wrong place and was planning to post another comment on the d.o. issue I believe.

**Comment by tadean** [comment] 2022-11-03 16:14
> It looks like trackleft2 noted that the libraries were removed in version 5. Is this still an issue? Other than that, it seems like it's easy enough to include the patch to solve the issue. And it doesn't seem like AZQS has any qualms about adding useful patches.

In regards to a patch, doesn't the `cweagans/composer-patches` method we use require that a package and its dependencies be downloaded first in order to be patched? How would we remove the dependency requirement? Patches on `composer.json` are a special case since composer is going to be reading the unmodified `composer.json` from the repository. Won't the dependencies already have been downloaded before a patch can be applied?

**Comment by tadean** [comment] 2022-11-03 17:18
> How will the usage of layouts for media and cards negatively impact AZQS? As far as I've seen, AZQS relies on custom-built paragraphs that utilize AZ Bootstrap. Since Layouts are part of core, I think Barrio adding more support there is a good thing.

Since the distribution doesn't use layouts to represent cards (and media, etc), using layouts for cards creates content that may have migration issues in the future. there are also indications that using layouts for content (e.g. as a paragraphs replacement) has some [performance problems](https://www.drupal.org/project/drupal/issues/2940755) compared to using it for block placement. That's one of the reasons we initially opted to use paragraphs over layout builder, I think.

> I think it would be good to explore using the color functionality the way Barrio does. That was one of the reasons why Barrio was selected in the first place.

Currently, our colors are part of `arizona-bootstrap` because it's used by other projects than only Quickstart. Allowing Barrio's style of color customization to users might also be a brand question.

 > On the contrary, Barrio acts as a good platform for setting up regions, templates, theme logic and UI-based tools for site builders. Boiling it down to just getting bootstrap is missing the point.

These points aren't being missed, these are the parts of the theme that we're hoping to retain, I think. The different mechanisms for how bootstrap gets included certainly aren't the **only** aspects of the theme, just a significant portion of it. What we're hoping to remove are cases and hooks that are never applicable to the distribution's situation or are just creating the need for theme overrides.

> Unused functionality is not a good reason to exclude the entire theme. There's scores of unused functionality in both Drupal core and in included contributed modules, and it's not like AZQS is looking to split from all of those.

The issue is that many cases of the unused functionality are requiring maintained code in our theme to "opt out" of. We've not experienced the same level of issue with Drupal itself or contrib modules I don't think.

**Comment by joshuasosa** [comment] 2022-11-04 14:24
> Since the distribution doesn't use layouts to represent cards (and media, etc), using layouts for cards creates content that may have migration issues in the future.

Barrio says: "Barrio 5.x ships with layouts defined using core layout_discovery module, these layouts can be used out of the box with Display Suite, Layout Builder or any other module that consumes layouts."

AZQS doesn't use Display Suite, Layout Builder nor does it consume layouts. I don't see how Barrio's support of it would negatively impact AZQS at all. It wouldn't think their inclusions would somehow surreptitiously override the Page content type and force in layouts in lieu of paragraphs.

> Currently, our colors are part of `arizona-bootstrap` because it's used by other projects than only Quickstart. Allowing Barrio's style of color customization to users might also be a brand question.

Colors were already removed from the subtheme from near the beginning of AZ Barrio's development. What I'd like to see is more pre-defined colored options such as colored headers. I believe to achieve that, we were considering utilizing Colors again in the future to create custom Color Sets. We could also set up something like a series of images with associated radio options to select other header color styles.

> These points aren't being missed, these are the parts of the theme that we're hoping to retain, I think. The different mechanisms for how bootstrap gets included certainly aren't the **only** aspects of the theme, just a significant portion of it. What we're hoping to remove are cases and hooks that are never applicable to the distribution's situation or are just creating the need for theme overrides.

> The issue is that many cases of the unused functionality are requiring maintained code in our theme to "opt out" of. We've not experienced the same level of issue with Drupal itself or contrib modules I don't think.

Again, the desire to remove unused functionality seems very much like a non-issue that does not warrant a complete departure. . It's akin to AZQS _never_ using Forum, Layout (at least for now), Comment, Tour, etc and therefore wanting to split from Drupal core. I think you may need to re-evaluate the claim that there hasn't been the same level of issue with Drupal itself, when AZQS includes 11 different Drupal core patches that were deemed critical enough for some aspect of project viability to necessitate adding them in.

As far as I've seen, with examples given above, opting out of some things has amounted to more-or-less one line of `unset()` to remove some vestigial base stylings. That's hardly a huge overhead to overcome some minor shortcomings. It should instead be cause to raise an issue in the Barrio issue queue about non-Bootstrap stylings.

**Comment by tadean** [comment] 2022-11-04 18:22
> As far as I've seen, with examples given above, opting out of some things has amounted to more-or-less one line of unset() to remove some vestigial base stylings.

Some things, of course. Other things have required a lot of refactoring to change. `unset()` also sometimes means our child theme has no equivalent of a parent theme variable which can allow regressions to creep in if the parent value changes.

> wanting to split from Drupal core

These things aren't equivalent, though. It's easy to convert a subtheme to a base theme. WIth the subtheme starterkit and some of the configuration we're not using removed, Barrio is a very reasonable size. Splitting from Drupal core would be an immense long term maintenance task (and not something we're considering anyway.) By contrast, the branch of Barrio we'd be splitting from has had one release this year.

>  It should instead be cause to raise an issue in the Barrio issue queue

I definitely agree. This is why we've been trying to pursue the [current longstanding issue](https://www.drupal.org/project/bootstrap_barrio/issues/3138347) we're concerned about. We haven't been successful with this route yet. I think we'd prefer to see issues fixed upstream if possible. Due to it being a composer.json change, this isn't something we can alter via a patch.

**Comment by tadean** [comment] 2022-11-04 20:42
**Note from our Friday meeting (11/4/22)**: We discussed that before any serious consideration of actually merging #2020 we should first do due diligence and ping our existing `bootstrap_barrio` issue again including maybe updating the patch if for the current branch heads (if necessary) to see if we can garner a response from the maintainer.

**Comment by joshuasosa** [comment] 2022-11-08 22:13
> Some things, of course. Other things have required a lot of refactoring to change. `unset()` also sometimes means our child theme has no equivalent of a parent theme variable which can allow regressions to creep in if the parent value changes.

The unsets are unsets of CSS files, so I don't think this is generally the case.
> These things aren't equivalent, though. It's easy to convert a subtheme to a base theme. WIth the subtheme starterkit and some of the configuration we're not using removed, Barrio is a very reasonable size. Splitting from Drupal core would be an immense long term maintenance task (and not something we're considering anyway.) By contrast, the branch of Barrio we'd be splitting from has had one release this year.

Yes they very much can be considered equivalent in terms of the philosophy employed for the move. It's one of the reasons and benefits of why Backdrop split from Drupal: being able to be more lean with development and make improvements faster. The difference with that project though is they continue to work with Drupal core developers on similar issues, where as this project would seemingly like to stop collaborating with others in the parent theme.

Obviously I am in minority opinion here, even so I initially selected this parent theme and put together most of the initial AZ Barrio package. I do not want to split from the parent theme, so I'll unfortunately be creating my own split of the child theme to be able to update to the latest Barrio versions.

**Comment by tadean** [comment] 2022-11-08 22:47
> The unsets are unsets of CSS files, so I don't think this is generally the case.

There are also unsets of form elements in theme forms and someelements which are programmatically generated by `bootstrap_barrio`'s regions and other factors. This means that the parent variable takes priority unless we specifically override it. CSS unsets aren't the factor I'm referring to (though there are some of those that are being `unset()`, yes)

> this project would seemingly like to stop collaborating with others

We have issues and patches submitted for many known issues we've discovered. (and not just for `barrio`) 

I want to stress the point that **we want** recent `bootstrap_barrio` bug fixes, but we have been **blocked from updating** because of this twitter bootstrap dependency issue. That means we must either hope the maintainer fixes the `composer.json` dependency issue or fork the theme and incorporate the parent changes manually (and leave out the bootstrap dependency). Due to the time the issue has been active, we have been examining latter, but I'd be just as happy with the former.

**Comment by joshuasosa** [comment] 2022-11-09 01:03
Including twbs is _not_ a showstopper and a poor reason to split the whole theme off.

Aside from that, have you tried including this in AZQS composer.json?
```
    "replace": {
        "twbs/bootstrap": "*"
    },
```

I tried it before and after and it seemed to skip it in my testing.

Before:

>   - Installing drupal/bootstrap_utilities (1.2.0): Extracting archive
>   - Installing twbs/bootstrap (v5.2.2): Extracting archive
>   - Installing drupal/bootstrap_barrio (5.5.6): Extracting archive

After:

>   - Installing drupal/bootstrap_utilities (1.2.0): Extracting archive
>   - Installing drupal/bootstrap_barrio (5.5.6): Extracting archive

**Comment by tadean** [comment] 2022-11-09 01:53
> Including twbs is not a showstopper and a poor reason to split the whole theme off.

It adds hundreds of files to pantheon artifacts and local development environments (which already builds slowly on environments where docker volume sharing is provided by NFS). It's really not desirable, and unnecessary.

> Aside from that, have you tried including this in AZQS composer.json?

```
    "replace": {
        "twbs/bootstrap": "*"
    },
```

I like this suggestion, good idea @joshuasosa ! This seems like a neat solution worth experimenting with. I'd be okay with something like that if there's consensus on the other issues voiced about barrio.

I'm curious if there are any adverse packagist effects for this in a published package in that we might show up as a `twbs/bootstrap` fork (but there're probably a lot of those).

**Comment by joshuasosa** [comment] 2022-12-08 21:56
If the plan is to continue with a split regardless of solutions brought up for the Barrio theme, then my next suggestion would be to  forego using anything from Barrio so as to not run into the potential for 'legacy' overhead in the future. 

Instead, the theme should be rebuilt be based on the new core starterkit_theme:
https://www.drupal.org/about/core/blog/new-starterkit-will-change-how-you-create-themes-in-drupal-10
https://www.drupal.org/docs/core-modules-and-themes/core-themes/starterkit-theme

starterkit_theme was made available as of Drupal 9.3. Although I disagree with _forking_ Barrio instead of working with the community or using workarounds (e.g., disabling component CSS files, disabling twbs bs repo, etc.), I wouldn't be opposed to a rebuild using starterkit_theme (or something similar).

**Comment by joeparsons** [comment] 2022-12-14 20:59
## 2022-12-14 Status update

- @tadean is going to make a draft PR that implements @joshuasosa's suggestion from (https://github.com/az-digital/az_quickstart/issues/690#issuecomment-1308050290

**Comment by joeparsons** [comment] 2022-12-14 21:04
## 2022-12-14 Status update

- We're not planning to make a final decision about until Jan 2023 at the earliest
- @tadean is going to make a draft PR that implements @joshuasosa's composer [suggestion from Nov 8](https://github.com/az-digital/az_quickstart/issues/690#issuecomment-1308050290)
- @joeparsons and @trackleft are going to add an additional comments to this issue explaining their remaining concerns with continuing to use Bootstrap Barrio
- We discussed @joshuasosa suggestion Re: the starterkit_theme and are generally in favor of the idea of looking into starterkit_theme further

**Comment by tadean** [comment] 2022-12-14 21:08
Draft PR for testing the implications of setting our theme to instead be a replacement for `twbs/bootstrap` to prevent the download of the bootstrap files, per @joshuasosa 's suggestion: https://github.com/az-digital/az_quickstart/pull/2096

**Comment by joeparsons** [comment] 2023-05-24 22:13
## Notes from discussion in our 2023-05-24 workshop:
- Consensus seems to be that updating latest supported TWBS 4 compatible version of Bootstrap Barrio instead of forking, at least for the foreseeable future (especially for the 2.7.0 minor release & D10 upgrade).
- We'll need to create a separate issue/PR for updating Bootstrap Barrio.
- We also plan to pursue the suggestion to use composer's `replace` functionality in our https://github.com/az-digital/arizona-bootstrap-packagist repo (see https://github.com/az-digital/arizona-bootstrap-packagist/pull/20)

**Closed by joeparsons** 2023-05-24 22:13 UTC
Labels: enhancement, high priority
