### ISSUE TITLE
Create "plan" or "release plan" issue template

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az_quickstart#2008] opened 2022-10-19 23:23 UTC
It would be useful to have an issue template for "plan" issues.  We've been creating these for planning what will be included in minor and patch releases but it would be nice to have some of the formatting already in place.

**Comment by trackleft** [comment] 2024-04-03 19:08
Duplicate of #1780

**Closed by trackleft** 2024-04-03 19:08 UTC
Labels: task
