### ISSUE TITLE
Person content type

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#93] opened 2020-04-09 23:35 UTC
Maintain current functionality... or use the User as the Person in the future.

**Comment by danahertzberg** [comment] 2020-11-17 23:46
Duplicate of https://app.zenhub.com/workspaces/quickstart-20-5e8f25351c5b8596956ebb92/issues/az-digital/az_quickstart/298

**Closed** 2020-11-17 23:46 UTC
Labels: Epic

**Comment by trackleft** [comment] 2024-10-09 21:14
It was determined that using the User entity type as content would be less ideal than adding a permission that allows authenticated users to edit their own content.

Related to: #3553
