### ISSUE TITLE
Iframe Video Thumbnails in Editor are Too Small

### ISSUE THREAD

**Issue by BradBarkel** [az-digital/az_quickstart#2979] opened 2023-12-06 17:20 UTC
## Problem/Motivation
We often have remote videos from sources (Panopto, Playposit, H5P) that aren't supported using the remote video embed menu so we have to add these iframes manually in CKEditor using the Source option. 

### Describe the bug
#2946 fixed a similar issue for videos added using the embed remote video menu, but in this case the issue occurs when manually adding iframe videos using the CKEditor5 Source option. #2693 and #2950 also seem somewhat related. 

Videos added as iframes using the CKEditor Source menu option display as small thumbnails in the editor view. Using the responsive embed wrapper and iframe classes (https://digital.arizona.edu/arizona-bootstrap/docs/2.0/utilities/embed/) don't seem to make a difference. Everything renders properly on the front end when published, but the videos the editor sees are very small thumbnails. In CKEditor4 when we added videos to our site in this manner they displayed at a more reasonable size, usually taking up the full width of the editor. 

Screenshots showing small thumbnail:
![image](https://github.com/az-digital/az_quickstart/assets/19657012/6708032e-7edb-4db7-930f-a08fe810e2b2)

![image](https://github.com/az-digital/az_quickstart/assets/19657012/ee6c4a39-60e1-42b5-967a-89747316d287)

### To Reproduce

- Edit existing content that contains an iframe video that was added through the CKEditor's Source option, 
- OR create new content and add an iframe video by clicking the Source menu button, 
- add the html code for the iframe, 
- click Source menu button again to display the editor view, 
- see the small video thumbnail on the page (screenshots above). 

## Proposed resolution
#2693 could be a solution, if other video providers were supported we wouldn't have to manually paste in iframe code, which can be burdensome for some not-so-technical content editors and often requires web developer intervention to get their content added to the site.

I'm not super familiar with the inner-workings of CKEditor, but it looks like in this case it injects a span with an 83px width between our wrapper div and the iframe element which limits the width and height of what is being displayed in the editor view.
![image](https://github.com/az-digital/az_quickstart/assets/19657012/404ab28c-2098-417c-bb1f-0db7b9f8fbef)
CKEditor4 does not inject a span here - see screenshot of code from CKEditor 4 -
![image](https://github.com/az-digital/az_quickstart/assets/19657012/24bc2820-6fd9-4a2c-a092-3d2a6e145152)

Adding min-width and aspect-ratio properties in devtools makes it look better in the editor view - perhaps adding those properties could be a solution?
![image](https://github.com/az-digital/az_quickstart/assets/19657012/3d3464cb-779a-4817-bc0b-e78a3db6ef2f)

  

### Expected behavior

Expected behavior is for these video thumbnails to display at a reasonable size, in the same or similar way they did when using CKEditor4.

Screenshot showing how this displays in CKEditor4, taking up full-width in the editor view
![image](https://github.com/az-digital/az_quickstart/assets/19657012/0eb09964-dfb4-419b-91c1-8982c774cb10)

### Desktop (please complete the following information):
 - OS: MacOS 13.6.2 (22G320)
 - Browser: reproducible in Chrome, Safari, and Firefox

## Additional context
None.

**Comment by joeparsons** [comment] 2023-12-06 21:26
Unfortunately we can't really support iframes manually added in CKEditor (especially with CKEditor 5) and don't really want to allow iframes in our standard text formats.

We're hoping to be able to accomodate embedding content from sources like these using the Media Remote module that @trackleft is exploring in #2693.  Going to close this is as not planned since it is effectively a duplicate of what we're hoping to do for that issue.

**Closed by joeparsons** 2023-12-06 21:26 UTC
Labels: bug, enhancement
