### ISSUE TITLE
Background patterns do not display for Text with Background

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#741] opened 2021-05-15 21:30 UTC
## Problem/Motivation
The triangles and trilines backgrounds to not display when selected on the Text with Background paragarph type

### Describe the bug
When I select triangles or trilines as the background pattern on Text with Background they do not seem to display in any of the combinations of colors/patterns that I try

### To Reproduce

1. Go to 'Add Content'
2. Click on 'Page'
3. Add 'Text with Background'
4. Select a Background Color and Background Pattern
5. Add text
6. Click Save
7. Verify if pattern appears

### Expected behavior

Triangles and trilines should appear as they do in QS1

##  Screenshots
Configuration:
![image](https://user-images.githubusercontent.com/10873398/118378625-f3c73d80-b589-11eb-939b-0538ceced496.png)

Display:
![image](https://user-images.githubusercontent.com/10873398/118378646-0477b380-b58a-11eb-9e36-d49288ef968a.png)

### Desktop (please complete the following information):
 - OS: MacOS Catalina
 - Browser Chrome
 - Version 90.0.4430.93

**Comment by danahertzberg** [comment] 2021-05-17 19:34
I'm seeing the same issue. I know it was working when the original PR was merged. So something might have happened between then and now.

https://github.com/az-digital/az_quickstart/pull/418

**Comment by joeparsons** [comment] 2021-05-20 01:07
I'm looking into this.  The issue is caused by incorrect image paths that exist in the minified version of arizona-bootstrap.css since version 2.0.7 (only the minified version is affected).  It looks like the issue is being caused by the CSS minification tool used by Arizona Bootstrap (clean-css-cli).

**Comment by joeparsons** [comment] 2021-05-20 01:17
https://github.com/az-digital/arizona-bootstrap/pull/288

**Comment by joeparsons** [comment] 2021-05-20 17:13
Fixed with #770

**Closed by joeparsons** 2021-05-20 17:13 UTC
Labels: backport, bug, high priority
