### ISSUE TITLE
Create "traditional" upstream option

### ISSUE THREAD

**Issue by barrettbaffert** [az-digital/az_quickstart#104] opened 2020-04-10 03:00 UTC

**Comment by camikazegreen** [comment] 2020-06-04 20:32
Duplicate of #55

**Closed by camikazegreen** 2020-06-04 20:32 UTC

**Comment by jwmoore1** [comment] 2020-06-04 21:03
@camikazegreen I'm not 100% sure this is a duplicate of #55. I think #55 references a composer-based upstream using features Pantheon hasn't released yet whereas this issue was meant to be more of a build artifact similar to what we use now.
