### ISSUE TITLE
Embed dialog boxes "x" to close button not visible on Mac (Saf, FF, Chr)

### ISSUE THREAD

**Issue by natebyerley** [az-digital/az_quickstart#1621] opened 2022-06-01 15:57 UTC
### Describe the bug

The "X" in upper right - to close a dialog box for embed (blocks, content) - in the CK editor is rendering in the same color (black) as top bar - thus it is not visible (though it is there).  Took me a while to figure this out - can cause a user to lose work on a page due to reloading the page to close out embed dialog pane if accidentally opened.

### To Reproduce

On a Mac, running FF, Chrome or Safari
Open a text content block > Click on any of 3 embed icons (images, content or blocks).  Note missing X to close dialog 

### Fix

Make X white against black background.
<img width="1189" alt="Screen Shot 2022-06-01 at 8 50 51 AM" src="https://user-images.githubusercontent.com/97116860/171447869-2da3a9a0-6c75-4435-ae6a-ac4de182028b.png">

<img width="1189" alt="Screen Shot 2022-06-01 at 8 50 54 AM" src="https://user-images.githubusercontent.com/97116860/171447905-471b6828-b42f-4a29-ae19-c8a744cfb562.png">

**Comment by joeparsons** [comment] 2022-06-01 18:48
I think this is probably a duplicate of #1071 (probably caused by the same underlying issue).

**Closed** 2022-06-03 18:55 UTC
