### ISSUE TITLE
az_paragraph_full_width_media_row migration has no default set for view mode

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1924] opened 2022-09-23 16:36 UTC
## Problem/Motivation
Migrating uaqs_full_width_media_row paragraphs from a QS1 site results in an error.

### Describe the bug
 `az_paragraph_full_width_media_row:view_mode_processed: No static mapping found for '''' and no default value provided for destination 'view_mode_processed'.  `

**Comment by joeparsons** [comment] 2022-09-23 17:39
Is this a duplicate of #1915?

**Comment by joeparsons** [comment] 2022-10-03 16:53
Duplicate of #1915.

**Closed by joeparsons** 2022-10-03 16:53 UTC
Labels: bug, migration
