### ISSUE TITLE
Add WorkBench Access module to Quickstart 

### ISSUE THREAD

**Issue by cpoff** [az-digital/az_quickstart#1972] opened 2022-10-04 20:24 UTC
Dana assigned this one to me. I'm going to add the WB Access module to the composer.json.

![Slack conversation that includes Ashley's how-to: ](https://user-images.githubusercontent.com/730076/193919119-ed1181be-14f1-4679-9151-6fd9ea540226.jpg)

**Comment by joeparsons** [comment] 2022-10-04 21:46
I believe this is a duplicate of #1908

**Comment by joeparsons** [comment] 2022-10-04 21:46
Duplicate of #1908

**Closed by joeparsons** 2022-10-04 21:46 UTC
