### ISSUE TITLE
When migrating html paragraphs from QS1 to QS2 with embedded media receive an error.

### ISSUE THREAD

**Issue by trackleft** [az-digital/az_quickstart#1452] opened 2022-04-04 18:30 UTC
### Describe the bug

```
  1/14 [==>-------------------------]   7% [error]  Drupal\entity_embed\Exception\EntityNotFoundException: Unable to load embedded file entity 59. in Drupal\entity_embed\Plugin\Filter\EntityEmbedFilter->process() (line 162 of /code/web/modules/contrib/entity_embed/src/Plugin/Filter/EntityEmbedFilter.php). 
 [error]  Drupal\entity_embed\Exception\EntityNotFoundException: Unable to load embedded file entity . in Drupal\entity_embed\Plugin\Filter\EntityEmbedFilter->process() (line 162 of /code/web/modules/contrib/entity_embed/src/Plugin/Filter/EntityEmbedFilter.php). 
 [warning] DOMDocument::loadHTML(): Tag drupal-entity invalid in Entity, line: 1 EntityEmbedProcess.php:212
```

Source site markup:
```
<drupal-entity data-align="center" data-embed-button="uaqs_files" data-entity-embed-display="file_entity:file_rendered" data-entity-embed-settings="{&quot;file_view_mode&quot;:&quot;uaqs_large&quot;}" data-entity-id="59" data-entity-label="File" data-entity-type="file" data-entity-uuid=""></drupal-entity>
<p>We encourage all students to get involved with campus programs and clubs. The UA has 500+ student clubs and organizations in addition to those that serve our Native American community. Make friends and find your passion! For more information, please check out <a href="https://asuatoday.arizona.edu/clubs/clubs-directory">ASUA Clubs Directory</a>.</p>
```

Destination site:

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/1023167/161607898-1d8dfd2a-9b01-4aba-be93-4b823a8b2797.png">

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1023167/161607986-2147887d-66bc-4173-86cc-5c0e87d0dcd1.png">

**Comment by danahertzberg** [comment] 2022-04-29 18:47
Potentially fixed with https://github.com/az-digital/az_quickstart/issues/1476

**Comment by trackleft** [comment] 2022-08-02 22:06
New patch available:
```
        "patches": {
            "az-digital/az_quickstart" {
                "Use HTML5 instead of \DOMDocument(https://github.com/az-digital/az_quickstart/issues/1523)": "https://patch-diff.githubusercontent.com/raw/az-digital/az_quickstart/pull/1739.diff"
            }
        }
```
`lando drush migrate:import az_paragraph_html --update`

Remove this patch when done with your migration.

If you run into issues with this patch, please report them on this issue.

**Comment by trackleft** [comment] 2022-08-05 20:50
There is a possibility that this commit resolves this issue for media: https://github.com/az-digital/az_quickstart/commit/1ed504de567524dce96ba31cdd35061441915733

In QS1 media is embedded using a `<drupal-entity>` tag
In QS2 media is embedded using a `<drupal-media>` tag

In QS1 blocks are embedded using a `<drupal-entity>` tag
In QS2 blocks are embedded using a `<drupal-entity>` tag


The error was thrown here: https://git.drupalcode.org/project/entity_embed/-/blob/8.x-1.x/src/Plugin/Filter/EntityEmbedFilter.php#L162


There is also a possibility that the `--continue-on-failure` flag should be used during the migration, to avoid seeing the error, since entity_embed seems to have a sensible default in place for when that exception is thrown.

**Comment by trackleft** [comment] 2022-08-05 21:00
This may just be happening with embedded blocks in the source site that havent' been migrated since there are no block migrations at the moment, and there is no implementation in our EntityEmbedProcess plugin.

https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php#L277-L280

**Comment by trackleft** [comment] 2022-08-05 21:03
The error messages aren't very clear about which source entity is causing it unfortunately, and so my original description, may be incorrect.

**Comment by joeparsons** [comment] 2022-10-26 23:37
@tadean shared in our 2022-10-26 Wendesday PR meeting that he found that these errors are at least partly being caused by some of the embedded entities existing in _card_ paragraphs on the source site and we don't currently use the entity embed process plugin on cards in our migration for card paragraphs.

**Closed** 2023-01-13 18:05 UTC
Labels: bug, migration
