### ISSUE TITLE
QS Course import fails in LAW

### ISSUE THREAD

**Issue by cpoff** [az-digital/az_quickstart#2177] opened 2023-01-25 17:27 UTC
## Problem/Motivation
Nearing end of the Law migration, I went to import the Spring 2023 courses from UAccess. Went into the Drupal UI on TEST > Configuration > Import Courses > "LAW"

[https://test-azs-law.pantheonsite.io/admin/config/az-quickstart/courses](https://test-azs-law.pantheonsite.io/admin/config/az-quickstart/courses)

### Describe the bug
The import begins, then craps out around 5%. Happens in all three environments (DEV/TEST/LIVE).

Error message:
`An AJAX HTTP error occurred.
HTTP Result Code: 504
Debugging information follows.
Path: /batch?id=62&op=do_nojs&op=do
StatusText: error
ResponseText: The application did not respond in time.`

After checking the Content section, just 16 new law courses were imported.

### To Reproduce

- Go to the TEST version on Law
- Navigate to the path spelled out above
- Enter "Law" to select the import section
- Activate the import

I tested on smaller batch jobs by importing categories with smaller course lists (NETV), and it completed. So I suspect it's just the larger batches causing the timeout.

##  Screenshots

![Screenshot 2023-01-25 at 10 25 13 AM](https://user-images.githubusercontent.com/730076/214636601-88ec5bc7-f643-4178-b037-78da46d9bea4.png)

**Comment by joeparsons** [comment] 2023-04-28 20:52
This is a duplicate of #1724

**Comment by joeparsons** [comment] 2023-04-28 20:53
This is a duplicate of #1724

**Closed by joeparsons** 2023-04-28 20:53 UTC
Labels: bug
