### ISSUE TITLE
Improve content editing experience of building pages with View paragraph type

### ISSUE THREAD

**Issue by smayden** [az-digital/az_quickstart#1224] opened 2022-01-14 20:06 UTC
## Motivation
In talking to content editors in a few departments, it is clear that using the View paragraph is not very intuitive. We could add help text or some other tweaks to make things clearer.

### Is your feature request related to a problem? Please describe.
- Content editors often don't know what the View paragraph is or how to use it (we have documentation on the Quickstart site - perhaps help text with a link to documentation?)
- It is hard for content editors to know what the varying display options do. We have examples on the Quickstart site, but they are cross-referenced from the View documentation) - improve documentation
- There is no indication in the interface what the arguments field is for or how to use it - Add help text that links to taxonomy under structure and also include info about how to make multiple arguments required (commas) or additiive (+).

## Proposed Resolution
Add help text and improve documentation.

### Roles and Permissions considerations
A clear and concise description of how each of the following roles would be impacted by this change:
- Content editor
- Content administrator

**Comment by trackleft** [comment] 2024-05-24 21:44
Duplicate of #2622

**Closed by trackleft** 2024-05-24 21:44 UTC
Labels: documentation, enhancement, low priority
